name: agular & asp core sample

on:
  workflow_dispatch:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .Net
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore Dependencies
      run: dotnet restore Angular-and-ASP.NET-Core-Sample-App.csproj

    - id: build
      name: build
      run: dotnet build Angular-and-ASP.NET-Core-Sample-App.csproj --no-restor

    - id: publish
      name: Publish
      run: dotnet publish "Angular-and-ASP.NET-Core-Sample-App.csproj" -c Relaease -o ./publish --self-contained -r linux-x64 /p:UseAppHost

    - name: Zip Artifact
      run: zip app.zip ./publish

    - id: upload
      name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-webapp
        path: app.zip