name: agular & asp core sample

on:
  workflow_dispatch:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .Net
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.204

    - name: Restore Dependencies
      run: dotnet Restore

    - id: build
      name: build
      run: dotnet build --no-retore